---
title: "Analysis_Code"
output: html_document
date: "2024-11-20"
---

To Do:

Extract data from API 
Categorize the neighborhoods by the criteria

Julia: grocery store distance
Amia: vehicles
Rosie: income

### Extract Data from API:  

HFAI  

```{r}
hfai_url <- "https://services1.arcgis.com/mVFRs7NF4iFitgbY/arcgis/rest/services/Hfai/FeatureServer/0/query?where=1%3D1&outFields=*&outSR=4326&f=json"

jsonData <- read_json(hfai_url, simplifyVector = TRUE)

hfai <- jsonData$features$attributes %>% 
  select(OBJECTID, CSA2010, hfai15, Shape__Area, Shape__Length)
head(hfai)
```


Median Income

```{r}
library(jsonlite)
library(tidyverse)

income_url <- "https://services1.arcgis.com/mVFRs7NF4iFitgbY/arcgis/rest/services/Mhhi/FeatureServer/0/query?outFields=*&where=1%3D1&f=geojson"

jsonData <- read_json(income_url, simplifyVector = TRUE)

med_income <- jsonData$features$properties %>% 
  select(OBJECTID, CSA2010, mhhi22, Shape__Area, Shape__Length)
head(med_income)
```

Percent of Vehicles Available

```{r}
vehicles_url <- "https://services1.arcgis.com/mVFRs7NF4iFitgbY/arcgis/rest/services/Novhcl/FeatureServer/0/query?where=1%3D1&outFields=*&outSR=4326&f=json"

jsonData <- read_json(vehicles_url, simplifyVector = TRUE)

vehicles <- jsonData$features$attributes %>% 
  select(OBJECTID, CSA2010, novhcl22, Shape__Area, Shape__Length)
head(med_income)
```

Grocery Store Location

```{r}
grocery_store_url <- "https://services1.arcgis.com/UWYHeuuJISiGmgXx/arcgis/rest/services/Grocery_Store/FeatureServer/0/query?where=1%3D1&outFields=*&outSR=4326&f=json"

jsonData <- read_json(grocery_store_url, simplifyVector = TRUE)

grocery_stores <- jsonData$features$attributes #%>% 
  select(OBJECTID, CSA2010, novhcl22, Shape__Area, Shape__Length)
head(med_income)
```
Check if all CSA boundaries match


```{r}
# install.packages("pak")
library(pak)
#pak::pkg_install("elipousson/mapbaltimore", dependencies = TRUE)
library(mapbaltimore)

length(get_area(
  type = "csa",
  location = grocery_stores$address
)$name)

mapbaltimore::csas$name
```

