---
title: "Food Accessibility in Baltimore by Neighborhood"
author: "Amia Graye, Rosie Quint, and Julia Martin"
output: 
  flexdashboard::flex_dashboard: 
    orientation: columns
    social: menu
    source_code: embed
    vertical_layout: fill
runtime: shiny
---

```{r}
library(shinydashboard)
library(dashboardthemes)

css <- 
".section.sidebar {
  top: 61px;
  background-color: rgba(235, 104, 100, 0.15);
}

.bg-primary {
  background-color: rgba(235, 104, 100, 0.7);
}

.nav-tabs-custom > .nav-tabs > li.active {
  border-top-color: rgba(235, 104, 100, 0.7);
}"

ui <- fluidPage(
  tags$head(tags$style(HTML(css))),
  tags$p("Hello, world!")
)

server <- function(input, output, session) {
}
shinyApp(ui, server)
```


```{r global, include=FALSE}
# load data in 'global' chunk so it can be shared by all users of the dashboard

```

```{r setup, include=FALSE}
library(flexdashboard)
library(DT)
library(shiny)
library(ggplot2)
library(dplyr)
library(tidyverse)
library(jsonlite)
library(mapbaltimore)
```

# Welcome and Introduction


# Categorization of Baltimore Neighborhoods


# Find Your Nearest Grocery Store


# Demographic Characteristics of Baltimore Neighborhoods


# Comparison to Prior Study Prior to Pandemic
