---
title: "Project 4 Write-Up: Team APIcons"
subtitle: "Food Accessibility Comparison in Baltimore Before and After the COVID-19 Pandemic"
authors: "Amia Graye, Julia Martin, Rosie Quint"
date: "December 19, 2024"
format: html
editor: visual
engine: knitr
---

# Introduction

The goal of our project is to compare food accessibility in Baltimore before and after the COVID-19 Pandemic and to understand patterns of food accessibility across Baltimore. We compiled our analysis into a Shiny Dashboard, [found here](https://jhu-statistical-computing-paradigms-project-4.shinyapps.io/Food_Accessibility_in_Baltimore_by_Neighborhood/?_gl=1*nd2m9u*_up*MQ..*_ga*MTcxODY0OTE0Ni4xNzM0NDkyODA3*_ga_HXP006LBGY*MTczNDQ5MjgwNi4xLjAuMTczNDQ5MjgwNi4wLjAuMA..*_ga_2C0WZ1JHG0*MTczNDQ5MjgwNi4xLjAuMTczNDQ5MjgwNi4wLjAuMA..), in which users can explore food accessibility in Baltimore by neighborhood by comparing each one's food accessibility rating, demographic characteristics, and the accessibility of grocery stores in Baltimore. This is a resource for residents of Baltimore to find their nearest grocery store and learn more about their neighborhood, or for policymakers who are seeking a broad overview of food accessibility in Baltimore to inform change. By employing the use of programming paradigms and R tools and packages we learned in class, we were successfully able to build on previous research in this area.

# Background and Motivation

The motivation for this project is to build upon [a 2018 study](https://planning.baltimorecity.gov/baltimore-food-policy-initiative/food-environment) conducted by the City of Baltimore Department of Planning and JHU Center for a Livable Future that identified neighborhoods in Baltimore City that are Healthy Food Priority Areas. However, our aim was to use more current data from 2022 to see if food accessibility has changed since that time, which also marks the period of before and after the pandemic. A Healthy Food Priority Area is a neighborhood that meets the following criteria:

1.  The average Healthy Food Availability Index (HFAI) score\* is in the lowest tier.

2.  The median household income is at or below 185% of the Federal Poverty Level

3.  Over 30% of households do not have a vehicle available

4.  The distance to a supermarket is more than ¼ mile\
    Source: City of Baltimore Department of Planning

\*The average HFAI score is a composite score that measures the availability of healthy food in a neighborhood. Each store (convenience store, supermarket, corner store etc.) is assigned a score based on its availability of healthy food options such as fresh produce and whole grains. The stores in each neighborhood are then averaged to get the neighborhood’s HFAI score.

This is an important topic to study because food accessibility is a key determinant of health. In 2018, about 25% of Baltimoreans lived in a Healthy Food Priority Area, which demonstrates that this is a critical issue to public health in Baltimore ([Misiaszek et al, 2018)](https://clf.jhsph.edu/publications/baltimore-citys-food-environment-report-2018-report). Additionally, the pandemic brought economic hardship which may have worsened food accessibility, and we were curious to study potential impacts that the pandemic had on accessing foods. Lastly, identifying which areas are at highest priority for improving access can inform city leaders to create a healthier Baltimore.

# Research Questions

1.  **How has food accessibility across different neighborhoods in Baltimore changed since 2018?**
2.  **Which groups of people have easier or harder access to healthy food in Baltimore?**

# Data Source

We used data from the Open Baltimore API, which is a free resource that provides data at the Community Statistical Area (CSA) level in Baltimore. We will refer to the CSAs as neighborhoods throughout the report and the boundaries can be found by looking at any of the maps on our dashboard. We extracted data on HFAI scores, percent of households without a vehicle, median household income, and grocery store location for each neighborhood which corresponds to the criteria necessary to classify a neighborhood as a Healthy Food Priority Area. We also extracted data on distribution of age, race, and education level for each neighborhood.

# Methods and Programming Paradigms

1.  We extracted data from Open Baltimore API using shell scripting executed in R. Here is an example of extracting a dataset from the API on HFAI scores from a JSON url.

```{bash}
curl -H "Accept: application/json" -X GET "https://services1.arcgis.com/mVFRs7NF4iFitgbY/arcgis/rest/services/Hfai/FeatureServer/0/query?where=1%3D1&outFields=*&outSR=4326&f=json" -o hfai.json
```

2.  We cleaned the data and manipulated each of the 4 datasets containing information on the Healthy Food Priority Area criteria so that we could join them together to categorize them into priority levels. We employed functional programming in this step. Here is an example of using a map() function to generate a list of neighborhoods in Baltimore that contain a supermarket. We also used the mapbaltimore package which can take an address as an input and output the neighborhood or CSA in which that address is located.

```{r, eval = F}
csas_with_store <- map(.x = add, .f = ~ get_area(type="csa", location = .x)$name)
```

3.  We constructed heatmaps that display the Healthy Food Priority for each neighborhood in Baltimore, both using the 2018 data and 2022 data.

4.  We conducted descriptive analysis on the demographic characteristics of each neighborhood and their corresponding Healthy Food Priority Levels.

5.  We compiled our maps and figures onto our dashboard and added interactive features for users to explore the food accessibility of different neighborhoods or the food accessibility patterns in neighborhoods with certain demographic features. We also added a widget for users to type in an address and find the nearest grocery store.

# Analysis

To analyze the demographics, we decided to make two pages: one focused on the summary statistics and distribution of the demographic categories and the other focused on the data visualization of the demographic categories in the perspective groups. The first column in the summary statistics page shows a table of the summary statistics (mean, median, and standard deviation) for each demographic variable, grouped by the priority level. The second column shows a bar chart of the distribution of each demographic variable, grouped by the priority level. 

The second page, the data visualization page, shows four different plots that analyze the demographic categories in the perspective groups. The first plot in the top left hand corner shows the distribution of the age groups based on priority levels in the form of boxplots. The second plot in the top right hand corner and the third plot in the bottom left hand corner both analyze the distribution of the racial populations based on the priority levels. The stacked bar chart gives a better visualization of the distribution between the racial groups, while the line chart portrays the distribution of the racial groups by their priority level. The last plot in the bottom right hand corner is a horizontal bar hcart that analyzes the distribution of the education levels based on the priority levels. 

# Results

Among the age groups, the group with the highest mean and median in high priority areas is the 25-64 group. The highest mean and median in medium priority areas is the 25-64 group, and the highest mean and median in the low priority areas is also the 25-64 group. This age group has the largest population in all priority areas, which is why it dominates in every priority level. This can be seen in the boxplot on the data visualization page, which shows the 25-64 age group on a completely different, higher scale than the other age groups. 

Among the racial groups, the group with the highest mean and median in high priority areas is the African American group. The highest mean and median in medium priority areas is the African American group, and the highest mean and median in the low priority areas is also the African American group. African Americans make up a majority of the Baltimore population, so it is not surprising that they are the largest racial group in all priority areas. This can be seen in the stacked bar chart and the line chart on the data visualization page, which shows the African American group as the largest group in all priority areas. 

What we found very interesting in the racial demographic analysis was the distribution of the white population amongst the priority levels. Most of the other racial demographics were fairly consistent in their distribution across the priority levels, but the white population was not. A similar pattern was seen amongst the Hispanic population, but the lack of symmetry in the white population was more pronounced. The white population was the largest in the low priority areas, but the smallest in the high priority areas, while the Hispanic population showed a slow downward trend from low to high priority level. This can be seen in the bar chart comparing the demographic categories by priority level on the summary statistics page and in the stakced bar chart and line chart of the data visualization page.

Among the education groups, the group with the highest mean and median in high priority areas is the group with a high school diploma or GED. The highest mean and median in medium priority areas is the group with a high school diploma or GED, and the highest mean and median in the low priority areas is also the group with a high school diploma or GED. People with a high school diploma or GED make a majority of the education population, so again, this group dominates in every priority level. Both education levels, less than a high school diploma and a high school diploma or GED, have an upward trend in the mean percentage values, going from low priority levels to high priority levels. It would have been really interesting to have the percent of population with a bachelor's degree or higher in the data, as this would have shown a more complete picture of the education distribution in Baltimore.

For the demographic groups, all of them have one category that is the largest in all priority levels, so it's difficult to conclude which groups of people have harder or easier access to health food in Baltimore. Based on population distribution alone, the White population are disproportionately higher in the high priority level compared to the African American population.

# Dashboard

# Technical Challenges

We ran into some challenges with extracting the data from the JSON files initially.

# Limitations

Our main limitation in this work is the data availability. We did not have access to recent HFAI data and grocery store locations, so we had to use data from 2018, so our results may differ if we were to use updated data for those categories. Additionally, the Community Statistical Area boundaries are large and there could be heterogeneity within neighborhoods that our analysis did not pick up on, so having more granular data could provide a more detailed analysis. Lastly, some of the criteria for Healthy Food Prioirty Areas, such as distance to a grocery store, have been debunked as poor forms of measuring food access based on [new studies](https://pmc.ncbi.nlm.nih.gov/articles/PMC5998793/#:~:text=Logistic%20regression%20analysis%20was%20used,not%20associated%20with%20food%20security.).

# Future Work

In the future, we would continue this work by recalculating updated HFAI scores for each neighborhood or devise another metric that is less resource intensive, as the data collection process to calculate this score involves a detailed questionnaire that must be taken into every single store in an area. This would also allow us to be able to repeat this analysis in other areas and other cities across the United States.

We would also attempt to acquire more granular data and rerun our analysis to understand more specifically which areas of Baltimore are lacking access to healthy food.

# References

Write up a summary of your final project and submit it to GitHub classroom.

Please explain the importance of the project, give an overview of the technical challenges, and what you learned. Also consider the following:

Write up quality: Is the write up clear on what was the question being investigated? What were the original goals and what was accomplished along the way? Was there previous work in this area? Do the figures have large enough legends and figure titles? Did you describe the data?

Is there a README.md in the repo you push to GitHub classroom summarizing key details about the project, including team members and an overview of the final project?

Have you linked to all code and data needed to reproduce your work?

Paradigm integration: How effectively does your project demonstrate multiple paradigms?

Functionality: Does the data analytic product work as intended? Are the components well-integrated?

Usability and documentation: Is the data analytic product easy to use/read and well-documented?

Originality and complexity: Does the project address a non-trivial statistical or programming problem with creativity?
